### ISSUE TITLE
Implement events for contract updates

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/service-listener#5]
### Description
Listen for events for contracts in the whitelist to update the following dynamic fields - `is_settled`, `collateral_pool_balance`, `last_trade_price`, `last_queried_price`.

Use `market-api` to update the contract record in the database.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [x] should use `market-api` to update a contract record in the database when receiving events for whitelisted contract addresses
- [x] unit tests

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
point of contact @eswarasai or @travisdmathis

**Comment by dmvt** [comment]
@eswarasai @travisdmathis What are the names of the events which signify an update?

**Comment by dmvt** [comment]
Taking a stab at it... After scanning the ABIs, I think the events are:

UpdatedLastPrice
ContractSettled
UpdatedUserBalance
UpdatedPoolBalance
QueryCompleted
QueryPrice

Please let me know if I'm missing any.
